openapi: 3.0.3
info:
  description: "API for managing courses, teachers, reviews, and users."
  title: Course Management API
  version: 1.0.0
servers:
- description: Production server
  url: https://api.example.com/v1
paths:
  /courses:
    get:
      operationId: getCourses
      parameters:
      - explode: true
        in: query
        name: only_available
        required: false
        schema:
          type: boolean
        style: form
      - explode: true
        in: query
        name: have_extern
        required: false
        schema:
          type: boolean
        style: form
      - explode: true
        in: query
        name: high_simplicity
        required: false
        schema:
          type: boolean
        style: form
      - explode: true
        in: query
        name: high_teacher_rating
        required: false
        schema:
          type: boolean
        style: form
      - description: Text to search courses
        explode: true
        in: query
        name: text_query
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCourses_200_response'
          description: A list of courses
        "403":
          description: User not authorized
      summary: Get courss
    post:
      operationId: postCourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseInfo'
        required: true
      responses:
        "201":
          description: Course created
        "403":
          description: User not authorized
      summary: Create a course
  /courses/{id}:
    get:
      operationId: getCourse
      parameters:
      - description: ID of the course
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseInfo'
          description: Course details
        "403":
          description: User not authorized
      summary: Get course details
  /courses/{id}/reviews:
    get:
      operationId: getCourseReviews
      parameters:
      - description: ID of the course
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      - description: Pagination cursor
        explode: true
        in: query
        name: cursor
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCourseReviews_200_response'
          description: List of course reviews
        "403":
          description: User not authorized
      summary: Get course reviews
  /teachers:
    get:
      operationId: getTeachers
      parameters:
      - description: Search query for teachers
        explode: true
        in: query
        name: query
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Teacher'
                type: array
          description: List of teachers
      summary: Search teachers
components:
  schemas:
    User:
      example:
        is_superuser: true
        name: name
        id: 0
        passport_token: passport_token
        profile_pic_url: profile_pic_url
      properties:
        id:
          title: id
          type: integer
        name:
          title: name
          type: string
        profile_pic_url:
          title: profile_pic_url
          type: string
        passport_token:
          title: passport_token
          type: string
        is_superuser:
          title: is_superuser
          type: boolean
      title: User
      type: object
    Teacher:
      example:
        average_grade: 1.4658129805029452
        name: name
        id: 6
      properties:
        id:
          title: id
          type: integer
        name:
          title: name
          type: string
        average_grade:
          title: average_grade
          type: number
      required:
      - id
      title: Teacher
      type: object
    Mark:
      example:
        name: name
        id: 6
        value: 1.4658129805029452
        max_value: 5.962133916683182
      properties:
        id:
          title: id
          type: integer
        name:
          title: name
          type: string
        value:
          title: value
          type: number
        max_value:
          title: max_value
          type: number
      title: Mark
      type: object
    CourseShortInfo:
      example:
        has_extern: true
        prerequisites:
        - name: name
          id: 5
        - name: name
          id: 5
        is_passed: true
        teacher:
          average_grade: 1.4658129805029452
          name: name
          id: 6
        name: name
        id: 0
        marks:
        - note: note
          name: name
          id: 5
          value: 2.3021358869347655
          max_value: 7.061401241503109
        - note: note
          name: name
          id: 5
          value: 2.3021358869347655
          max_value: 7.061401241503109
        recredit_available: true
      properties:
        id:
          title: id
          type: integer
        name:
          title: name
          type: string
        is_passed:
          title: is_passed
          type: boolean
        has_extern:
          title: has_extern
          type: boolean
        recredit_available:
          title: recredit_available
          type: boolean
        teacher:
          $ref: '#/components/schemas/Teacher'
        prerequisites:
          items:
            $ref: '#/components/schemas/CourseShortInfo_prerequisites_inner'
          title: prerequisites
          type: array
        marks:
          items:
            $ref: '#/components/schemas/CourseShortInfo_marks_inner'
          title: marks
          type: array
      required:
      - has_extern
      - id
      - is_passed
      - marks
      - name
      - prerequisites
      - recredit_available
      - teacher
      title: CourseShortInfo
      type: object
    CourseInfo:
      allOf:
      - $ref: '#/components/schemas/CourseShortInfo'
      - properties:
          general_description:
            type: string
          extern_description:
            type: string
          recredit_description:
            type: string
        required:
        - general_description
        type: object
      example:
        has_extern: true
        prerequisites:
        - name: name
          id: 5
        - name: name
          id: 5
        is_passed: true
        teacher:
          average_grade: 1.4658129805029452
          name: name
          id: 6
        extern_description: extern_description
        name: name
        general_description: general_description
        recredit_description: recredit_description
        id: 0
        marks:
        - note: note
          name: name
          id: 5
          value: 2.3021358869347655
          max_value: 7.061401241503109
        - note: note
          name: name
          id: 5
          value: 2.3021358869347655
          max_value: 7.061401241503109
        recredit_available: true
      title: CourseInfo
      type: object
    Grade:
      example:
        dislikes: 2
        likes: 5
      properties:
        likes:
          title: likes
          type: integer
        dislikes:
          title: dislikes
          type: integer
      required:
      - dislikes
      - likes
      title: Grade
      type: object
    Review:
      example:
        is_recredit: true
        author:
          is_superuser: true
          name: name
          id: 0
          passport_token: passport_token
          profile_pic_url: profile_pic_url
        is_extern: true
        is_hidden: true
        marks:
        - name: name
          id: 6
          value: 1.4658129805029452
          max_value: 5.962133916683182
        - name: name
          id: 6
          value: 1.4658129805029452
          max_value: 5.962133916683182
        text: text
        grades:
          dislikes: 2
          likes: 5
      properties:
        author:
          $ref: '#/components/schemas/User'
        marks:
          items:
            $ref: '#/components/schemas/Mark'
          title: marks
          type: array
        text:
          title: text
          type: string
        is_extern:
          title: is_extern
          type: boolean
        is_recredit:
          title: is_recredit
          type: boolean
        is_hidden:
          title: is_hidden
          type: boolean
        grades:
          $ref: '#/components/schemas/Grade'
      required:
      - grades
      - marks
      title: Review
      type: object
    getCourses_200_response:
      example:
        courses:
        - has_extern: true
          prerequisites:
          - name: name
            id: 5
          - name: name
            id: 5
          is_passed: true
          teacher:
            average_grade: 1.4658129805029452
            name: name
            id: 6
          name: name
          id: 0
          marks:
          - note: note
            name: name
            id: 5
            value: 2.3021358869347655
            max_value: 7.061401241503109
          - note: note
            name: name
            id: 5
            value: 2.3021358869347655
            max_value: 7.061401241503109
          recredit_available: true
        - has_extern: true
          prerequisites:
          - name: name
            id: 5
          - name: name
            id: 5
          is_passed: true
          teacher:
            average_grade: 1.4658129805029452
            name: name
            id: 6
          name: name
          id: 0
          marks:
          - note: note
            name: name
            id: 5
            value: 2.3021358869347655
            max_value: 7.061401241503109
          - note: note
            name: name
            id: 5
            value: 2.3021358869347655
            max_value: 7.061401241503109
          recredit_available: true
      properties:
        courses:
          items:
            $ref: '#/components/schemas/CourseShortInfo'
          title: courses
          type: array
      title: getCourses_200_response
      type: object
    getCourseReviews_200_response:
      example:
        next_cursor: next_cursor
        reviews:
        - is_recredit: true
          author:
            is_superuser: true
            name: name
            id: 0
            passport_token: passport_token
            profile_pic_url: profile_pic_url
          is_extern: true
          is_hidden: true
          marks:
          - name: name
            id: 6
            value: 1.4658129805029452
            max_value: 5.962133916683182
          - name: name
            id: 6
            value: 1.4658129805029452
            max_value: 5.962133916683182
          text: text
          grades:
            dislikes: 2
            likes: 5
        - is_recredit: true
          author:
            is_superuser: true
            name: name
            id: 0
            passport_token: passport_token
            profile_pic_url: profile_pic_url
          is_extern: true
          is_hidden: true
          marks:
          - name: name
            id: 6
            value: 1.4658129805029452
            max_value: 5.962133916683182
          - name: name
            id: 6
            value: 1.4658129805029452
            max_value: 5.962133916683182
          text: text
          grades:
            dislikes: 2
            likes: 5
      properties:
        reviews:
          items:
            $ref: '#/components/schemas/Review'
          title: reviews
          type: array
        next_cursor:
          title: next_cursor
          type: string
      title: getCourseReviews_200_response
      type: object
    CourseShortInfo_prerequisites_inner:
      example:
        name: name
        id: 5
      properties:
        id:
          title: id
          type: integer
        name:
          title: name
          type: string
      title: CourseShortInfo_prerequisites_inner
      type: object
    CourseShortInfo_marks_inner:
      allOf:
      - $ref: '#/components/schemas/Mark'
      - properties:
          note:
            type: string
        type: object
      example:
        note: note
        name: name
        id: 5
        value: 2.3021358869347655
        max_value: 7.061401241503109
      title: CourseShortInfo_marks_inner
      type: object
